databases:
  - name: dilan_co_postgres
    databaseName: dilan_co_production
    user: dilan_co
    plan: starter

services:
  - type: web
    name: dilan_co
    runtime: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dilan_co_postgres
          property: connectionString
      - key: POSTGRES_USER
        fromDatabase:
          name: dilan_co_postgres
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: dilan_co_postgres
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: dilan_co_postgres
          property: host
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"