default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dilan_co_development

test:
  <<: *default
  database: dilan_co_test

production:
  <<: *default
